// Generated by 'unplugin-auto-import'
export {}
declare global {
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const onMount: typeof import('svelte')['onMount']
  const writable: typeof import('svelte/store')['writable']
}
